# Generated by Django 5.1.4 on 2024-12-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
