# Generated by Django 5.1.4 on 2024-12-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertoken",
            name="max_attempt",
            field=models.IntegerField(default=10),
        ),
    ]
