# Generated by Django 5.1.4 on 2024-12-18 02:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_expired_by_usertoken_expired_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="usertoken",
            constraint=models.UniqueConstraint(
                fields=("token",), name="validate_token"
            ),
        ),
    ]
